name: CI/CD Digital Ocean
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: appleboy/ssh-action@v0.1.4 # This is the action
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          passphrase: ${{ secrets.SSH_PASSPHRASE }}

          script: |
            rm -rf Vita
            git clone https://github.com/Vita-App/Vita.git
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh   
            cd Vita/api && npm install
            pm2 stop vita-server
            pm2 start dist/src/index.js --name "vita-server"
            echo 'Deployment successful to digital ocean'
